'''
Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibonacci(limit):
    fibonacci = [1, 2]
    i = 1
    while fibonacci[i] < limit:
        fibonacci.append(fibonacci[i] + fibonacci[i - 1])
        i += 1
    
    return fibonacci

def even_sum(arr):
    even_sum = 0
    for num in arr:
        if not (num % 2):
            even_sum += num
    
    return even_sum

def solution(limit):
    solution = even_sum(fibonacci(limit))

    print(
        "The sum of the even-valued terms below " + str(limit),
        "is " + str(solution) + "."
    )

solution(4000000)